# ~/.config/mise/config.toml

[tools]
python = ["3.8", "3.13"]
mockery = "latest"
go = "latest"
awscli = "latest"
gradle = "latest"
jq = "latest"
maven = "latest"
ruby = "latest"
svu = "latest"
terraform = "latest"
golangci-lint = "latest"
goreleaser = "latest"
kotlin = "latest"
buf = "latest"
rust = "latest"
zig = "latest"
java = "corretto-23.0.1.8"


[plugins]
# The default go-swagger plugin fucks up on linux/arm
go-swagger = "https://github.com/Slijkhuis/asdf-go-swagger"

[settings]
# plugins can read the versions files used by other version managers (if enabled by the plugin)
# for example, .nvmrc in the case of node's nvm
legacy_version_file = false                     # enabled by default (unlike asdf)

# configure `rtx install` to always keep the downloaded archive
always_keep_download = false        # deleted after install by default
always_keep_install = false         # deleted on failure by default

# configure how frequently (in minutes) to fetch updated plugin repository changes
# this is updated whenever a new runtime is installed
# (note: this isn't currently implemented but there are plans to add it: https://github.com/jdx/rtx/issues/128)
plugin_autoupdate_last_check_duration = '1 week' # set to 0 to disable updates

# config files with these prefixes will be trusted by default
trusted_config_paths = [
    '~/dev',
]

verbose = false     # set to true to see full installation output, see `RTX_VERBOSE`
asdf_compat = true  # set to true to ensure .tool-versions will be compatible with asdf, see `RTX_ASDF_COMPAT`
jobs = 6            # number of plugins or runtimes to install in parallel. The default is `4`.
raw = false         # set to true to directly pipe plugins to stdin/stdout/stderr
yes = false         # set to true to automatically answer yes to all prompts

disable_default_shorthands = false # disable the default shorthands, see `RTX_DISABLE_DEFAULT_SHORTHANDS`
# disable_tools = ['node']           # disable specific tools, generally used to turn off core tools
experimental = true
