[tools]
awscli = "latest"
buf = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
golangci-lint = "latest"
goreleaser = "latest"
jq = "latest"
mockery = "latest"
python = "3.14"
ruby = "latest"
rust = "latest"
usage = "latest"
svu = "latest"
terraform = "latest"
zig = "latest"
node = "26.5.0"
"ubi:caarlos0/svu" = "3.4.1"

[settings]
trusted_config_paths = ['~/dev']
asdf_compat = true
experimental = true

[settings.status]
show_tools = true
